<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ps1</string>
		<string>psm1</string>
	</array>
	<key>name</key>
	<string>PowerShell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((?&lt;=function )([a-zA-Z:\-\.0-9_])+)</string>
			<key>name</key>
			<string>entity.name.function.powershell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((--%).*(?=#))</string>
			<key>name</key>
			<string>source.powershell</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lineComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#repository</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arithmeticOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignmentOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comparisonOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bitwiseOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logicalOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unaryOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#otherOperators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logicalNot</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scriptBlock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hereString</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hashTable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#stringDoubleQuoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#stringSingleQuoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numericConstants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#generiFunctionMatch</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#powershellGeneric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parameters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#netClasses</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reservedWords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arithmeticOperators</key>
		<dict>
			<key>match</key>
			<string>((?&lt;=(\d|\s))(\+|-|/|\*|%)(?=(\d|\s)))</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.powershell</string>
		</dict>
		<key>assignmentOperators</key>
		<dict>
			<key>match</key>
			<string>((?&lt;=\s)(=|\+=|-=|/=|%=)(?=\s))</string>
			<key>name</key>
			<string>keyword.operator.assignment.powershell</string>
		</dict>
		<key>bitwiseOperators</key>
		<dict>
			<key>match</key>
			<string>(-(?i:band|bor|bxor|bnot|shr|shl)\b)</string>
			<key>name</key>
			<string>keyword.operator.bitwise.powershell</string>
		</dict>
		<key>blockComments</key>
		<dict>
			<key>begin</key>
			<string>(&lt;#)</string>
			<key>end</key>
			<string>(#&gt;)</string>
			<key>name</key>
			<string>comment.block.powershell</string>
		</dict>
		<key>comparisonOperators</key>
		<dict>
			<key>match</key>
			<string>(-(?i:eq|ceq|ne|cne|gt|cgt|lt|clt|le|cle|ge|cge|match|cmatch|notmatch|cnotmatch|replace|creplace|like|clike|notlike|cnotlike|in|cin|notin|cnotin|contains|ccontains|notcontains|cnotcontains)\b)</string>
			<key>name</key>
			<string>keyword.operator.comparison.powershell</string>
		</dict>
		<key>debugComments</key>
		<dict>
			<key>match</key>
			<string>(DEBUG!)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>generiFunctionMatch</key>
		<dict>
			<key>match</key>
			<string>(\b(?i:Add|Clear|Close|Copy|Enter|Exit|Find|Format|Get|Hide|Join|Lock|Move|New|Open|Optimize|Pop|Push|Redo|Remove|Rename|Reset|Resize|Search|Select|Set|Show|Skip|Split|Step|Switch|Undo|Unlock|Watch|Backup|Checkpoint|Compare|Compress|Convert|ConvertFrom|ConvertTo|Dismount|Edit|Expand|Export|Group|Import|Initialize|Limit|Merge|Mount|Out|Publish|Restore|Save|Sync|Unpublish|Update|Approve|Assert|Complete|Confirm|Deny|Disable|Enable|Install|Invoke|Register|Request|Restart|Resume|Start|Stop|Submit|Suspend|Uninstall|Unregister|Wait|Debug|Measure|Ping|Repair|Resolve|Test|Trace|Connect|Disconnect|Read|Receive|Send|Write|Block|Grant|Protect|Revoke|Unblock|Unprotect|Use)-(?i:\w+)\b)</string>
			<key>name</key>
			<string>support.function.generic.powershell</string>
		</dict>
		<key>hashTable</key>
		<dict>
			<key>begin</key>
			<string>(@\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.hashtable.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringSingleQuoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stringDoubleQuoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generiFunctionMatch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numericConstants</string>
				</dict>
			</array>
		</dict>
		<key>hereString</key>
		<dict>
			<key>begin</key>
			<string>(@")</string>
			<key>end</key>
			<string>("@)</string>
			<key>name</key>
			<string>string.quoted.double.herestring.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>lineComments</key>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>end</key>
			<string>(\n)</string>
			<key>name</key>
			<string>comment.line.number-sign.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#debugComments</string>
				</dict>
			</array>
		</dict>
		<key>logicalNot</key>
		<dict>
			<key>match</key>
			<string>(!)</string>
			<key>name</key>
			<string>keyword.operator.other.powershell</string>
		</dict>
		<key>logicalOperators</key>
		<dict>
			<key>match</key>
			<string>(-(?i:and|or|xor|not)\b)</string>
			<key>name</key>
			<string>keyword.operator.logical.powershell</string>
		</dict>
		<key>netClasses</key>
		<dict>
			<key>match</key>
			<string>((?&lt;=\[)((\w|\[|\]|\.)*)(?=\]))</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<key>numericConstants</key>
		<dict>
			<key>match</key>
			<string>(\b(\d+)((,|\.)*)(\d*)?(?i:kb|mb|gb)?\b)</string>
			<key>name</key>
			<string>constant.numeric.powershell</string>
		</dict>
		<key>numericFormatting</key>
		<dict>
			<key>match</key>
			<string>((:[NnCcDdPpXx])(\d*))</string>
			<key>name</key>
			<string>constant.numeric.powershell</string>
		</dict>
		<key>otherOperators</key>
		<dict>
			<key>match</key>
			<string>(-(?i:as|is|isnot|split|join|f)\b)</string>
			<key>name</key>
			<string>keyword.operator.other.powershell</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>match</key>
			<string>((?&lt;=\s)-(\w+))</string>
			<key>name</key>
			<string>variable.parameter.powershell</string>
		</dict>
		<key>powershellGeneric</key>
		<dict>
			<key>match</key>
			<string>(\b(?i:foreach-object|tee-object|where-object|sort-object)\b)</string>
			<key>name</key>
			<string>support.function.generic.powershell</string>
		</dict>
		<key>reservedWords</key>
		<dict>
			<key>match</key>
			<string>(\b(?&lt;!-)(?i:begin|process|exit|break|filter|return|catch|finally|sequence|class|for|switch|continue|foreach|throw|data|from|trap|define|function|try|do|if|until|dynamicparam|in|using|else|inlinescript|var|elseif|parallel|while|end|param|workflow|where)\b(?!-))</string>
			<key>name</key>
			<string>keyword.control.powershell</string>
		</dict>
		<key>scriptBlock</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.scriptblock.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numericFormatting</string>
				</dict>
			</array>
		</dict>
		<key>stringDoubleQuoted</key>
		<dict>
			<key>begin</key>
			<string>((?&lt;!\")\")</string>
			<key>end</key>
			<string>(\"(?!\"))</string>
			<key>name</key>
			<string>string.quoted.double.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringEscapeChars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subExpression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scriptBlock</string>
				</dict>
			</array>
		</dict>
		<key>stringEscapeChars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(`[0abfnrtv"'$`])</string>
					<key>name</key>
					<string>constant.character.escape.powershell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>("")</string>
					<key>name</key>
					<string>constant.character.escape.powershell</string>
				</dict>
			</array>
		</dict>
		<key>stringSingleQuoted</key>
		<dict>
			<key>begin</key>
			<string>((?&lt;!')')</string>
			<key>end</key>
			<string>('(?!'))</string>
			<key>name</key>
			<string>string.quoted.single.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringSingleQuotedDouble</string>
				</dict>
			</array>
		</dict>
		<key>stringSingleQuotedDouble</key>
		<dict>
			<key>match</key>
			<string>('')</string>
			<key>name</key>
			<string>constant.character.escape.powershell</string>
		</dict>
		<key>subExpression</key>
		<dict>
			<key>begin</key>
			<string>(\$\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>meta.subexpression.powershell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>unaryOperators</key>
		<dict>
			<key>match</key>
			<string>(\+\+|--)</string>
			<key>name</key>
			<string>keyword.operator.unary.powershell</string>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\$)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(\w+))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.language.powershell</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\$)(\{)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(\w+)(\}))</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.powershell</string>
	<key>uuid</key>
	<string>3cd82bc0-3786-4ae1-99f0-41f26c81e268</string>
</dict>
</plist>
